services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: restaurant-swagger-ui
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      API_URL: http://localhost:8080/v3/api-docs
    depends_on:
      api-gateway-service:
        condition: service_started

  mysql-admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: restaurant-mysql-admin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8091:80"
    depends_on:
      reservation-db:
        condition: service_healthy
      loyalty-db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: restaurant-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@restaurant.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      menu-db:
        condition: service_healthy

  mongo-express:
    image: mongo-express:latest
    container_name: restaurant-mongo-express
    restart: on-failure
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: aggregator-db
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      aggregator-db:
        condition: service_healthy
