# This is a Spring Boot configuration file in YAML format.
# It defines settings for the loyalty-service application.

# Server configuration
server:
  port: 8083  # The port on which the application will run.
  error:
    include-message: always

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.restaurantreservation: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Spring configuration for "default" profile
spring:
  application:
    name: loyalty-service
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:loyalty-service-db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
# Spring configuration for "docker" profile
spring:
  application:
    name: loyalty-service
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://loyalty-db:3306/loyalty_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: mysql
      mode: always
      data-locations: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
# Spring configuration for "testing" profile
spring:
  application:
    name: loyalty-service
  config:
    activate:
      on-profile: testing
  datasource:
    url: jdbc:h2:mem:loyaltydb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: embedded
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
