# This is a Spring Boot configuration file in YAML format.
# It defines settings for the api-gateway-service application.

# Server configuration
server:
  port: 8080  # The port on which the application will run.

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.restaurantreservation: TRACE

# Spring configuration for "default" profile
spring:
  application:
    name: api-gateway-service
  web:
    error:
      include-message: always
  config:
    activate:
      on-profile: default

microservices:
  reservation:
    base-url: http://localhost:8081
  menu:
    base-url: http://localhost:8082
  loyalty:
    base-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
# Spring configuration for "docker" profile
spring:
  application:
    name: api-gateway-service
  config:
    activate:
      on-profile: docker

microservices:
  reservation:
    base-url: http://reservation-service:8081
  menu:
    base-url: http://menu-service:8082
  loyalty:
    base-url: http://loyalty-service:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
