spring.application.name=api-gateway-service
server.port=${SERVER_PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

microservices.reservation.base-url=${RESERVATION_SERVICE_BASE_URL:http://localhost:8081}
microservices.menu.base-url=${MENU_SERVICE_BASE_URL:http://localhost:8082}
microservices.loyalty.base-url=${LOYALTY_SERVICE_BASE_URL:http://localhost:8083}
